### ISSUE TITLE
Brainstorm project ideas

### ISSUE THREAD

**Issue by Pobyeda** [Pobyeda/CSCI3511-Final-Project#1]
AC:

- Write a list of potential projects
- Pick project

**Comment by Pobyeda** [comment]
1) Wifi mobile RC robot
2) Black Box project

**Comment by jknight1725** [comment]
3. Garden moisture/humidity sensor
4. Obd-ii car diagnostics (Do something with the data?)

**Comment by Pobyeda** [comment]
Let's set due date for this issue. Maybe let's pick project next week on Mon. 

So, due 08/26/2019, so we can move forward and plan project. 

Feel free to add more project ideas, so we can discuss it on Mon.

**Comment by Pobyeda** [comment]
1. Wifi mobile RC robot
2. Black Box project
3. SmartHouse related project. Some sort of IoT with Arduino.
4. Garden moisture/humidity sensor
5. Obd-ii car diagnostics (Do something with the data?)
6. Weather station
7. iRF signal finder. "iFriends Finders"
8. Rubik cube solver
9. "Arduboi" game & console

**Comment by Pobyeda** [comment]
"Smart House Arduino"
- Weather - Temp, Humidity, Wind speed, Atmosphere pressure. 
- Alarm - Clock synchronize, Use display, be able to set Alarm (speaker). 
- Pass data between two, use wifi.

**Comment by Pobyeda** [comment]
Robot. Done.
